root: true
plugins:
  - flowtype
extends:
  - plugin:flowtype/recommended
  - prettier
  - plugin:react/recommended
parser: "@babel/eslint-parser"
settings:
  react:
    version: "16"
env:
  browser: true
  es6: true
  mocha: true
  node: true
globals:
  "$": true
  inkdrop: true
rules:
  no-useless-escape: 0
  prefer-const: 2
  no-unused-vars:
    - 2
    -
      argsIgnorePattern: ^_
      varsIgnorePattern: ^_
  react/display-name: 0
